version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    restart: always
    ports:
    - 443:443
    networks:
    - inception_network
    hostname: nginx
    volumes:
    - wpdata:/var/www/html/wordpress

  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
    - dbdata:/var/lib/mysql
    expose:
    - "3306"
    networks:
    - inception_network
    hostname: mariadb
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
      args:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    depends_on:
    - mariadb
    volumes:
    - wpdata:/var/www/html/wordpress
    restart: always
    expose:
    - "9000"
    networks:
    - inception_network
    hostname: wordpress


volumes:
  wpdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wp_data
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/db_da
networks:
  inception_network:
